apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: env-cont
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: POD_GREETING
      value: "Welcome"
    - name: POD_FAREWELL
      value:  "We dont stop!"